# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bf27599e-ce5b-4124-b59c-bcb069f72fb3";
      fsType = "ext4";
    };

  fileSystems."/mnt/nvme" =
    { device = "/dev/disk/by-uuid/dae26402-a2d8-46a9-bce1-bc1e62dd5dec";
      fsType = "ext4";
	    options = [
      "defaults"
      "noatime"
      "errors=remount-ro"
      "nofail"
      "rw"
      "users"
      "exec"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0A3C-2CC6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e5c6ac95-c755-413c-8069-c5f29237c6d3";
	      options = [ "defaults" "discard=once" ]; } #Nie zajeżdzaj mocno SSD gdy jest na nim swap
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
